### ISSUE TITLE
Estratégias de Engenharia de Software

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T01-DidasBistro#3]
- [x] Qual o referencial utilizado para estabelecer a estratégia de esw?

Considerações:
**Foco em Arquitetura:**
RAD: Parcialmente correto. No RAD, a arquitetura geralmente evolui durante o processo, com foco inicial na prototipagem.
Scrum: Parcialmente correto. O Scrum não prescreve um foco específico em arquitetura.

**Qualidade Técnica:**
RAD: Parcialmente correto. No RAD, a qualidade técnica é garantida pela rápida construção e teste de protótipos; ajustes são feitos conforme feedback.

**Práticas de Desenvolvimento:**
RAD: Parcialmente correto. O RAD foca na prototipagem e validação rápida, com menos práticas técnicas estruturadas.

**Escalabilidade:**
RAD: Parcialmente correto. O RAD é escalável para projetos de pequena a média escala; em projetos maiores, pode enfrentar desafios devido à sua natureza menos formal.

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated information about RAD and Scrum in the comparative table to address the criteria and provide more accurate descriptions of the methodologies.

You can review changes in this commit: https://github.com/lattaai12/mdsreq-fga-unb-2024.2-T01-DidasBistro-3/commit/bddca898cc64f16b5e9be27f8b3f8ac18d048467.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Mateushqms** [comment]
Os ajustes foram feitos. O referencial foi os critérios proposto por Gupta nos slides do professor e um desejo de possuir alguns rituais do scrum para a formalização do projeto.
